repos:
  # Sort imports automatically
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort
  #       name: isort
  #       args: ["--profile", "black"]

  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black
        args: ["--line-length=79"]

  # # Lint code with Flake8
  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.3.0
  #   hooks:
  #     - id: flake8

  # Check for syntax errors and common bugs
  # - repo: https://github.com/pre-commit/mirrors-pylint
  #   rev: v3.0.0a5
  #   hooks:
  #     - id: pylint

  # Ensure YAML, JSON, etc. are valid
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
